import Foundation

struct Country: Identifiable {
    let id: String
    let name: String
    let flag: String
    let isoCode: String
    
    init(name: String, flag: String, isoCode: String) {
        self.name = name
        self.flag = flag
        self.isoCode = isoCode
        self.id = isoCode
    }
}

enum CountryDatabase {
    static let all: [Country] = [
        Country(name: "Afghanistan", flag: "🇦🇫", isoCode: "AF"),
        Country(name: "Albania", flag: "🇦🇱", isoCode: "AL"),
        Country(name: "Algeria", flag: "🇩🇿", isoCode: "DZ"),
        Country(name: "Andorra", flag: "🇦🇩", isoCode: "AD"),
        Country(name: "Angola", flag: "🇦🇴", isoCode: "AO"),
        Country(name: "Antigua and Barbuda", flag: "🇦🇬", isoCode: "AG"),
        Country(name: "Argentina", flag: "🇦🇷", isoCode: "AR"),
        Country(name: "Armenia", flag: "🇦🇲", isoCode: "AM"),
        Country(name: "Australia", flag: "🇦🇺", isoCode: "AU"),
        Country(name: "Austria", flag: "🇦🇹", isoCode: "AT"),
        Country(name: "Azerbaijan", flag: "🇦🇿", isoCode: "AZ"),
        Country(name: "Bahamas", flag: "🇧🇸", isoCode: "BS"),
        Country(name: "Bahrain", flag: "🇧🇭", isoCode: "BH"),
        Country(name: "Bangladesh", flag: "🇧🇩", isoCode: "BD"),
        Country(name: "Barbados", flag: "🇧🇧", isoCode: "BB"),
        Country(name: "Belarus", flag: "🇧🇾", isoCode: "BY"),
        Country(name: "Belgium", flag: "🇧🇪", isoCode: "BE"),
        Country(name: "Belize", flag: "🇧🇿", isoCode: "BZ"),
        Country(name: "Benin", flag: "🇧🇯", isoCode: "BJ"),
        Country(name: "Bhutan", flag: "🇧🇹", isoCode: "BT"),
        Country(name: "Bolivia", flag: "🇧🇴", isoCode: "BO"),
        Country(name: "Bosnia and Herzegovina", flag: "🇧🇦", isoCode: "BA"),
        Country(name: "Botswana", flag: "🇧🇼", isoCode: "BW"),
        Country(name: "Brazil", flag: "🇧🇷", isoCode: "BR"),
        Country(name: "Brunei", flag: "🇧🇳", isoCode: "BN"),
        Country(name: "Bulgaria", flag: "🇧🇬", isoCode: "BG"),
        Country(name: "Burkina Faso", flag: "🇧🇫", isoCode: "BF"),
        Country(name: "Burundi", flag: "🇧🇮", isoCode: "BI"),
        Country(name: "Cabo Verde", flag: "🇨🇻", isoCode: "CV"),
        Country(name: "Cambodia", flag: "🇰🇭", isoCode: "KH"),
        Country(name: "Cameroon", flag: "🇨🇲", isoCode: "CM"),
        Country(name: "Canada", flag: "🇨🇦", isoCode: "CA"),
        Country(name: "Central African Republic", flag: "🇨🇫", isoCode: "CF"),
        Country(name: "Chad", flag: "🇹🇩", isoCode: "TD"),
        Country(name: "Chile", flag: "🇨🇱", isoCode: "CL"),
        Country(name: "China", flag: "🇨🇳", isoCode: "CN"),
        Country(name: "Colombia", flag: "🇨🇴", isoCode: "CO"),
        Country(name: "Comoros", flag: "🇰🇲", isoCode: "KM"),
        Country(name: "Congo", flag: "🇨🇬", isoCode: "CG"),
        Country(name: "Costa Rica", flag: "🇨🇷", isoCode: "CR"),
        Country(name: "Cote d'Ivoire", flag: "🇨🇮", isoCode: "CI"),
        Country(name: "Croatia", flag: "🇭🇷", isoCode: "HR"),
        Country(name: "Cuba", flag: "🇨🇺", isoCode: "CU"),
        Country(name: "Cyprus", flag: "🇨🇾", isoCode: "CY"),
        Country(name: "Czechia", flag: "🇨🇿", isoCode: "CZ"),
        Country(name: "Democratic Republic of the Congo", flag: "🇨🇩", isoCode: "CD"),
        Country(name: "Denmark", flag: "🇩🇰", isoCode: "DK"),
        Country(name: "Djibouti", flag: "🇩🇯", isoCode: "DJ"),
        Country(name: "Dominica", flag: "🇩🇲", isoCode: "DM"),
        Country(name: "Dominican Republic", flag: "🇩🇴", isoCode: "DO"),
        Country(name: "Ecuador", flag: "🇪🇨", isoCode: "EC"),
        Country(name: "Egypt", flag: "🇪🇬", isoCode: "EG"),
        Country(name: "El Salvador", flag: "🇸🇻", isoCode: "SV"),
        Country(name: "Equatorial Guinea", flag: "🇬🇶", isoCode: "GQ"),
        Country(name: "Eritrea", flag: "🇪🇷", isoCode: "ER"),
        Country(name: "Estonia", flag: "🇪🇪", isoCode: "EE"),
        Country(name: "Eswatini", flag: "🇸🇿", isoCode: "SZ"),
        Country(name: "Ethiopia", flag: "🇪🇹", isoCode: "ET"),
        Country(name: "Fiji", flag: "🇫🇯", isoCode: "FJ"),
        Country(name: "Finland", flag: "🇫🇮", isoCode: "FI"),
        Country(name: "France", flag: "🇫🇷", isoCode: "FR"),
        Country(name: "Gabon", flag: "🇬🇦", isoCode: "GA"),
        Country(name: "Gambia", flag: "🇬🇲", isoCode: "GM"),
        Country(name: "Georgia", flag: "🇬🇪", isoCode: "GE"),
        Country(name: "Germany", flag: "🇩🇪", isoCode: "DE"),
        Country(name: "Ghana", flag: "🇬🇭", isoCode: "GH"),
        Country(name: "Greece", flag: "🇬🇷", isoCode: "GR"),
        Country(name: "Grenada", flag: "🇬🇩", isoCode: "GD"),
        Country(name: "Guatemala", flag: "🇬🇹", isoCode: "GT"),
        Country(name: "Guinea", flag: "🇬🇳", isoCode: "GN"),
        Country(name: "Guinea-Bissau", flag: "🇬🇼", isoCode: "GW"),
        Country(name: "Guyana", flag: "🇬🇾", isoCode: "GY"),
        Country(name: "Haiti", flag: "🇭🇹", isoCode: "HT"),
        Country(name: "Holy See", flag: "🇻🇦", isoCode: "VA"),
        Country(name: "Honduras", flag: "🇭🇳", isoCode: "HN"),
        Country(name: "Hungary", flag: "🇭🇺", isoCode: "HU"),
        Country(name: "Iceland", flag: "🇮🇸", isoCode: "IS"),
        Country(name: "India", flag: "🇮🇳", isoCode: "IN"),
        Country(name: "Indonesia", flag: "🇮🇩", isoCode: "ID"),
        Country(name: "Iran", flag: "🇮🇷", isoCode: "IR"),
        Country(name: "Iraq", flag: "🇮🇶", isoCode: "IQ"),
        Country(name: "Ireland", flag: "🇮🇪", isoCode: "IE"),
        Country(name: "Israel", flag: "🇮🇱", isoCode: "IL"),
        Country(name: "Italy", flag: "🇮🇹", isoCode: "IT"),
        Country(name: "Jamaica", flag: "🇯🇲", isoCode: "JM"),
        Country(name: "Japan", flag: "🇯🇵", isoCode: "JP"),
        Country(name: "Jordan", flag: "🇯🇴", isoCode: "JO"),
        Country(name: "Kazakhstan", flag: "🇰🇿", isoCode: "KZ"),
        Country(name: "Kenya", flag: "🇰🇪", isoCode: "KE"),
        Country(name: "Kiribati", flag: "🇰🇮", isoCode: "KI"),
        Country(name: "Kosovo", flag: "🇽🇰", isoCode: "XK"),
        Country(name: "Kuwait", flag: "🇰🇼", isoCode: "KW"),
        Country(name: "Kyrgyzstan", flag: "🇰🇬", isoCode: "KG"),
        Country(name: "Laos", flag: "🇱🇦", isoCode: "LA"),
        Country(name: "Latvia", flag: "🇱🇻", isoCode: "LV"),
        Country(name: "Lebanon", flag: "🇱🇧", isoCode: "LB"),
        Country(name: "Lesotho", flag: "🇱🇸", isoCode: "LS"),
        Country(name: "Liberia", flag: "🇱🇷", isoCode: "LR"),
        Country(name: "Libya", flag: "🇱🇾", isoCode: "LY"),
        Country(name: "Liechtenstein", flag: "🇱🇮", isoCode: "LI"),
        Country(name: "Lithuania", flag: "🇱🇹", isoCode: "LT"),
        Country(name: "Luxembourg", flag: "🇱🇺", isoCode: "LU"),
        Country(name: "Madagascar", flag: "🇲🇬", isoCode: "MG"),
        Country(name: "Malawi", flag: "🇲🇼", isoCode: "MW"),
        Country(name: "Malaysia", flag: "🇲🇾", isoCode: "MY"),
        Country(name: "Maldives", flag: "🇲🇻", isoCode: "MV"),
        Country(name: "Mali", flag: "🇲🇱", isoCode: "ML"),
        Country(name: "Malta", flag: "🇲🇹", isoCode: "MT"),
        Country(name: "Marshall Islands", flag: "🇲🇭", isoCode: "MH"),
        Country(name: "Mauritania", flag: "🇲🇷", isoCode: "MR"),
        Country(name: "Mauritius", flag: "🇲🇺", isoCode: "MU"),
        Country(name: "Mexico", flag: "🇲🇽", isoCode: "MX"),
        Country(name: "Micronesia", flag: "🇫🇲", isoCode: "FM"),
        Country(name: "Moldova", flag: "🇲🇩", isoCode: "MD"),
        Country(name: "Monaco", flag: "🇲🇨", isoCode: "MC"),
        Country(name: "Mongolia", flag: "🇲🇳", isoCode: "MN"),
        Country(name: "Montenegro", flag: "🇲🇪", isoCode: "ME"),
        Country(name: "Morocco", flag: "🇲🇦", isoCode: "MA"),
        Country(name: "Mozambique", flag: "🇲🇿", isoCode: "MZ"),
        Country(name: "Myanmar", flag: "🇲🇲", isoCode: "MM"),
        Country(name: "Namibia", flag: "🇳🇦", isoCode: "NA"),
        Country(name: "Nauru", flag: "🇳🇷", isoCode: "NR"),
        Country(name: "Nepal", flag: "🇳🇵", isoCode: "NP"),
        Country(name: "Netherlands", flag: "🇳🇱", isoCode: "NL"),
        Country(name: "New Zealand", flag: "🇳🇿", isoCode: "NZ"),
        Country(name: "Nicaragua", flag: "🇳🇮", isoCode: "NI"),
        Country(name: "Niger", flag: "🇳🇪", isoCode: "NE"),
        Country(name: "Nigeria", flag: "🇳🇬", isoCode: "NG"),
        Country(name: "North Korea", flag: "🇰🇵", isoCode: "KP"),
        Country(name: "North Macedonia", flag: "🇲🇰", isoCode: "MK"),
        Country(name: "Norway", flag: "🇳🇴", isoCode: "NO"),
        Country(name: "Oman", flag: "🇴🇲", isoCode: "OM"),
        Country(name: "Pakistan", flag: "🇵🇰", isoCode: "PK"),
        Country(name: "Palau", flag: "🇵🇼", isoCode: "PW"),
        Country(name: "Palestine", flag: "🇵🇸", isoCode: "PS"),
        Country(name: "Panama", flag: "🇵🇦", isoCode: "PA"),
        Country(name: "Papua New Guinea", flag: "🇵🇬", isoCode: "PG"),
        Country(name: "Paraguay", flag: "🇵🇾", isoCode: "PY"),
        Country(name: "Peru", flag: "🇵🇪", isoCode: "PE"),
        Country(name: "Philippines", flag: "🇵🇭", isoCode: "PH"),
        Country(name: "Poland", flag: "🇵🇱", isoCode: "PL"),
        Country(name: "Portugal", flag: "🇵🇹", isoCode: "PT"),
        Country(name: "Qatar", flag: "🇶🇦", isoCode: "QA"),
        Country(name: "Romania", flag: "🇷🇴", isoCode: "RO"),
        Country(name: "Russia", flag: "🇷🇺", isoCode: "RU"),
        Country(name: "Rwanda", flag: "🇷🇼", isoCode: "RW"),
        Country(name: "Saint Kitts and Nevis", flag: "🇰🇳", isoCode: "KN"),
        Country(name: "Saint Lucia", flag: "🇱🇨", isoCode: "LC"),
        Country(name: "Saint Vincent and the Grenadines", flag: "🇻🇨", isoCode: "VC"),
        Country(name: "Samoa", flag: "🇼🇸", isoCode: "WS"),
        Country(name: "San Marino", flag: "🇸🇲", isoCode: "SM"),
        Country(name: "Sao Tome and Principe", flag: "🇸🇹", isoCode: "ST"),
        Country(name: "Saudi Arabia", flag: "🇸🇦", isoCode: "SA"),
        Country(name: "Senegal", flag: "🇸🇳", isoCode: "SN"),
        Country(name: "Serbia", flag: "🇷🇸", isoCode: "RS"),
        Country(name: "Seychelles", flag: "🇸🇨", isoCode: "SC"),
        Country(name: "Sierra Leone", flag: "🇸🇱", isoCode: "SL"),
        Country(name: "Singapore", flag: "🇸🇬", isoCode: "SG"),
        Country(name: "Slovakia", flag: "🇸🇰", isoCode: "SK"),
        Country(name: "Slovenia", flag: "🇸🇮", isoCode: "SI"),
        Country(name: "Solomon Islands", flag: "🇸🇧", isoCode: "SB"),
        Country(name: "Somalia", flag: "🇸🇴", isoCode: "SO"),
        Country(name: "South Africa", flag: "🇿🇦", isoCode: "ZA"),
        Country(name: "South Korea", flag: "🇰🇷", isoCode: "KR"),
        Country(name: "South Sudan", flag: "🇸🇸", isoCode: "SS"),
        Country(name: "Spain", flag: "🇪🇸", isoCode: "ES"),
        Country(name: "Sri Lanka", flag: "🇱🇰", isoCode: "LK"),
        Country(name: "Sudan", flag: "🇸🇩", isoCode: "SD"),
        Country(name: "Suriname", flag: "🇸🇷", isoCode: "SR"),
        Country(name: "Sweden", flag: "🇸🇪", isoCode: "SE"),
        Country(name: "Switzerland", flag: "🇨🇭", isoCode: "CH"),
        Country(name: "Syria", flag: "🇸🇾", isoCode: "SY"),
        Country(name: "Taiwan", flag: "🇹🇼", isoCode: "TW"),
        Country(name: "Tajikistan", flag: "🇹🇯", isoCode: "TJ"),
        Country(name: "Tanzania", flag: "🇹🇿", isoCode: "TZ"),
        Country(name: "Thailand", flag: "🇹🇭", isoCode: "TH"),
        Country(name: "Timor-Leste", flag: "🇹🇱", isoCode: "TL"),
        Country(name: "Togo", flag: "🇹🇬", isoCode: "TG"),
        Country(name: "Tonga", flag: "🇹🇴", isoCode: "TO"),
        Country(name: "Trinidad and Tobago", flag: "🇹🇹", isoCode: "TT"),
        Country(name: "Tunisia", flag: "🇹🇳", isoCode: "TN"),
        Country(name: "Turkey", flag: "🇹🇷", isoCode: "TR"),
        Country(name: "Turkmenistan", flag: "🇹🇲", isoCode: "TM"),
        Country(name: "Tuvalu", flag: "🇹🇻", isoCode: "TV"),
        Country(name: "Uganda", flag: "🇺🇬", isoCode: "UG"),
        Country(name: "Ukraine", flag: "🇺🇦", isoCode: "UA"),
        Country(name: "United Arab Emirates", flag: "🇦🇪", isoCode: "AE"),
        Country(name: "United Kingdom", flag: "🇬🇧", isoCode: "GB"),
        Country(name: "United States", flag: "🇺🇸", isoCode: "US"),
        Country(name: "Uruguay", flag: "🇺🇾", isoCode: "UY"),
        Country(name: "Uzbekistan", flag: "🇺🇿", isoCode: "UZ"),
        Country(name: "Vanuatu", flag: "🇻🇺", isoCode: "VU"),
        Country(name: "Venezuela", flag: "🇻🇪", isoCode: "VE"),
        Country(name: "Vietnam", flag: "🇻🇳", isoCode: "VN"),
        Country(name: "Yemen", flag: "🇾🇪", isoCode: "YE"),
        Country(name: "Zambia", flag: "🇿🇲", isoCode: "ZM"),
        Country(name: "Zimbabwe", flag: "🇿🇼", isoCode: "ZW")
    ]
}
