import Foundation

struct Country: Identifiable {
    let id: String
    let name: String
    let flag: String
    let isoCode: String
    let continent: String
    
    init(name: String, flag: String, isoCode: String, continent: String) {
        self.name = name
        self.flag = flag
        self.isoCode = isoCode
        self.continent = continent
        self.id = isoCode
    }
}

enum CountryDatabase {
    static let all: [Country] = [
        Country(name: "Afghanistan", flag: "🇦🇫", isoCode: "AF", continent: "Asia"),
        Country(name: "Albania", flag: "🇦🇱", isoCode: "AL", continent: "Europe"),
        Country(name: "Algeria", flag: "🇩🇿", isoCode: "DZ", continent: "Africa"),
        Country(name: "Andorra", flag: "🇦🇩", isoCode: "AD", continent: "Europe"),
        Country(name: "Angola", flag: "🇦🇴", isoCode: "AO", continent: "Africa"),
        Country(name: "Antigua and Barbuda", flag: "🇦🇬", isoCode: "AG", continent: "North America"),
        Country(name: "Argentina", flag: "🇦🇷", isoCode: "AR", continent: "South America"),
        Country(name: "Armenia", flag: "🇦🇲", isoCode: "AM", continent: "Asia"),
        Country(name: "Australia", flag: "🇦🇺", isoCode: "AU", continent: "Oceania"),
        Country(name: "Austria", flag: "🇦🇹", isoCode: "AT", continent: "Europe"),
        Country(name: "Azerbaijan", flag: "🇦🇿", isoCode: "AZ", continent: "Asia"),
        Country(name: "Bahamas", flag: "🇧🇸", isoCode: "BS", continent: "North America"),
        Country(name: "Bahrain", flag: "🇧🇭", isoCode: "BH", continent: "Asia"),
        Country(name: "Bangladesh", flag: "🇧🇩", isoCode: "BD", continent: "Asia"),
        Country(name: "Barbados", flag: "🇧🇧", isoCode: "BB", continent: "North America"),
        Country(name: "Belarus", flag: "🇧🇾", isoCode: "BY", continent: "Europe"),
        Country(name: "Belgium", flag: "🇧🇪", isoCode: "BE", continent: "Europe"),
        Country(name: "Belize", flag: "🇧🇿", isoCode: "BZ", continent: "North America"),
        Country(name: "Benin", flag: "🇧🇯", isoCode: "BJ", continent: "Africa"),
        Country(name: "Bhutan", flag: "🇧🇹", isoCode: "BT", continent: "Asia"),
        Country(name: "Bolivia", flag: "🇧🇴", isoCode: "BO", continent: "South America"),
        Country(name: "Bosnia and Herzegovina", flag: "🇧🇦", isoCode: "BA", continent: "Europe"),
        Country(name: "Botswana", flag: "🇧🇼", isoCode: "BW", continent: "Africa"),
        Country(name: "Brazil", flag: "🇧🇷", isoCode: "BR", continent: "South America"),
        Country(name: "Brunei", flag: "🇧🇳", isoCode: "BN", continent: "Asia"),
        Country(name: "Bulgaria", flag: "🇧🇬", isoCode: "BG", continent: "Europe"),
        Country(name: "Burkina Faso", flag: "🇧🇫", isoCode: "BF", continent: "Africa"),
        Country(name: "Burundi", flag: "🇧🇮", isoCode: "BI", continent: "Africa"),
        Country(name: "Cabo Verde", flag: "🇨🇻", isoCode: "CV", continent: "Africa"),
        Country(name: "Cambodia", flag: "🇰🇭", isoCode: "KH", continent: "Asia"),
        Country(name: "Cameroon", flag: "🇨🇲", isoCode: "CM", continent: "Africa"),
        Country(name: "Canada", flag: "🇨🇦", isoCode: "CA", continent: "North America"),
        Country(name: "Central African Republic", flag: "🇨🇫", isoCode: "CF", continent: "Africa"),
        Country(name: "Chad", flag: "🇹🇩", isoCode: "TD", continent: "Africa"),
        Country(name: "Chile", flag: "🇨🇱", isoCode: "CL", continent: "South America"),
        Country(name: "China", flag: "🇨🇳", isoCode: "CN", continent: "Asia"),
        Country(name: "Colombia", flag: "🇨🇴", isoCode: "CO", continent: "South America"),
        Country(name: "Comoros", flag: "🇰🇲", isoCode: "KM", continent: "Africa"),
        Country(name: "Congo", flag: "🇨🇬", isoCode: "CG", continent: "Africa"),
        Country(name: "Costa Rica", flag: "🇨🇷", isoCode: "CR", continent: "North America"),
        Country(name: "Cote d'Ivoire", flag: "🇨🇮", isoCode: "CI", continent: "Africa"),
        Country(name: "Croatia", flag: "🇭🇷", isoCode: "HR", continent: "Europe"),
        Country(name: "Cuba", flag: "🇨🇺", isoCode: "CU", continent: "North America"),
        Country(name: "Cyprus", flag: "🇨🇾", isoCode: "CY", continent: "Asia"),
        Country(name: "Czechia", flag: "🇨🇿", isoCode: "CZ", continent: "Europe"),
        Country(name: "Democratic Republic of the Congo", flag: "🇨🇩", isoCode: "CD", continent: "Africa"),
        Country(name: "Denmark", flag: "🇩🇰", isoCode: "DK", continent: "Europe"),
        Country(name: "Djibouti", flag: "🇩🇯", isoCode: "DJ", continent: "Africa"),
        Country(name: "Dominica", flag: "🇩🇲", isoCode: "DM", continent: "North America"),
        Country(name: "Dominican Republic", flag: "🇩🇴", isoCode: "DO", continent: "North America"),
        Country(name: "Ecuador", flag: "🇪🇨", isoCode: "EC", continent: "South America"),
        Country(name: "Egypt", flag: "🇪🇬", isoCode: "EG", continent: "Africa"),
        Country(name: "El Salvador", flag: "🇸🇻", isoCode: "SV", continent: "North America"),
        Country(name: "Equatorial Guinea", flag: "🇬🇶", isoCode: "GQ", continent: "Africa"),
        Country(name: "Eritrea", flag: "🇪🇷", isoCode: "ER", continent: "Africa"),
        Country(name: "Estonia", flag: "🇪🇪", isoCode: "EE", continent: "Europe"),
        Country(name: "Eswatini", flag: "🇸🇿", isoCode: "SZ", continent: "Africa"),
        Country(name: "Ethiopia", flag: "🇪🇹", isoCode: "ET", continent: "Africa"),
        Country(name: "Fiji", flag: "🇫🇯", isoCode: "FJ", continent: "Oceania"),
        Country(name: "Finland", flag: "🇫🇮", isoCode: "FI", continent: "Europe"),
        Country(name: "France", flag: "🇫🇷", isoCode: "FR", continent: "Europe"),
        Country(name: "Gabon", flag: "🇬🇦", isoCode: "GA", continent: "Africa"),
        Country(name: "Gambia", flag: "🇬🇲", isoCode: "GM", continent: "Africa"),
        Country(name: "Georgia", flag: "🇬🇪", isoCode: "GE", continent: "Asia"),
        Country(name: "Germany", flag: "🇩🇪", isoCode: "DE", continent: "Europe"),
        Country(name: "Ghana", flag: "🇬🇭", isoCode: "GH", continent: "Africa"),
        Country(name: "Greece", flag: "🇬🇷", isoCode: "GR", continent: "Europe"),
        Country(name: "Grenada", flag: "🇬🇩", isoCode: "GD", continent: "North America"),
        Country(name: "Guatemala", flag: "🇬🇹", isoCode: "GT", continent: "North America"),
        Country(name: "Guinea", flag: "🇬🇳", isoCode: "GN", continent: "Africa"),
        Country(name: "Guinea-Bissau", flag: "🇬🇼", isoCode: "GW", continent: "Africa"),
        Country(name: "Guyana", flag: "🇬🇾", isoCode: "GY", continent: "South America"),
        Country(name: "Haiti", flag: "🇭🇹", isoCode: "HT", continent: "North America"),
        Country(name: "Holy See", flag: "🇻🇦", isoCode: "VA", continent: "Europe"),
        Country(name: "Honduras", flag: "🇭🇳", isoCode: "HN", continent: "North America"),
        Country(name: "Hungary", flag: "🇭🇺", isoCode: "HU", continent: "Europe"),
        Country(name: "Iceland", flag: "🇮🇸", isoCode: "IS", continent: "Europe"),
        Country(name: "India", flag: "🇮🇳", isoCode: "IN", continent: "Asia"),
        Country(name: "Indonesia", flag: "🇮🇩", isoCode: "ID", continent: "Asia"),
        Country(name: "Iran", flag: "🇮🇷", isoCode: "IR", continent: "Asia"),
        Country(name: "Iraq", flag: "🇮🇶", isoCode: "IQ", continent: "Asia"),
        Country(name: "Ireland", flag: "🇮🇪", isoCode: "IE", continent: "Europe"),
        Country(name: "Israel", flag: "🇮🇱", isoCode: "IL", continent: "Asia"),
        Country(name: "Italy", flag: "🇮🇹", isoCode: "IT", continent: "Europe"),
        Country(name: "Jamaica", flag: "🇯🇲", isoCode: "JM", continent: "North America"),
        Country(name: "Japan", flag: "🇯🇵", isoCode: "JP", continent: "Asia"),
        Country(name: "Jordan", flag: "🇯🇴", isoCode: "JO", continent: "Asia"),
        Country(name: "Kazakhstan", flag: "🇰🇿", isoCode: "KZ", continent: "Asia"),
        Country(name: "Kenya", flag: "🇰🇪", isoCode: "KE", continent: "Africa"),
        Country(name: "Kiribati", flag: "🇰🇮", isoCode: "KI", continent: "Oceania"),
        Country(name: "Kosovo", flag: "🇽🇰", isoCode: "XK", continent: "Europe"),
        Country(name: "Kuwait", flag: "🇰🇼", isoCode: "KW", continent: "Asia"),
        Country(name: "Kyrgyzstan", flag: "🇰🇬", isoCode: "KG", continent: "Asia"),
        Country(name: "Laos", flag: "🇱🇦", isoCode: "LA", continent: "Asia"),
        Country(name: "Latvia", flag: "🇱🇻", isoCode: "LV", continent: "Europe"),
        Country(name: "Lebanon", flag: "🇱🇧", isoCode: "LB", continent: "Asia"),
        Country(name: "Lesotho", flag: "🇱🇸", isoCode: "LS", continent: "Africa"),
        Country(name: "Liberia", flag: "🇱🇷", isoCode: "LR", continent: "Africa"),
        Country(name: "Libya", flag: "🇱🇾", isoCode: "LY", continent: "Africa"),
        Country(name: "Liechtenstein", flag: "🇱🇮", isoCode: "LI", continent: "Europe"),
        Country(name: "Lithuania", flag: "🇱🇹", isoCode: "LT", continent: "Europe"),
        Country(name: "Luxembourg", flag: "🇱🇺", isoCode: "LU", continent: "Europe"),
        Country(name: "Madagascar", flag: "🇲🇬", isoCode: "MG", continent: "Africa"),
        Country(name: "Malawi", flag: "🇲🇼", isoCode: "MW", continent: "Africa"),
        Country(name: "Malaysia", flag: "🇲🇾", isoCode: "MY", continent: "Asia"),
        Country(name: "Maldives", flag: "🇲🇻", isoCode: "MV", continent: "Asia"),
        Country(name: "Mali", flag: "🇲🇱", isoCode: "ML", continent: "Africa"),
        Country(name: "Malta", flag: "🇲🇹", isoCode: "MT", continent: "Europe"),
        Country(name: "Marshall Islands", flag: "🇲🇭", isoCode: "MH", continent: "Oceania"),
        Country(name: "Mauritania", flag: "🇲🇷", isoCode: "MR", continent: "Africa"),
        Country(name: "Mauritius", flag: "🇲🇺", isoCode: "MU", continent: "Africa"),
        Country(name: "Mexico", flag: "🇲🇽", isoCode: "MX", continent: "North America"),
        Country(name: "Micronesia", flag: "🇫🇲", isoCode: "FM", continent: "Oceania"),
        Country(name: "Moldova", flag: "🇲🇩", isoCode: "MD", continent: "Europe"),
        Country(name: "Monaco", flag: "🇲🇨", isoCode: "MC", continent: "Europe"),
        Country(name: "Mongolia", flag: "🇲🇳", isoCode: "MN", continent: "Asia"),
        Country(name: "Montenegro", flag: "🇲🇪", isoCode: "ME", continent: "Europe"),
        Country(name: "Morocco", flag: "🇲🇦", isoCode: "MA", continent: "Africa"),
        Country(name: "Mozambique", flag: "🇲🇿", isoCode: "MZ", continent: "Africa"),
        Country(name: "Myanmar", flag: "🇲🇲", isoCode: "MM", continent: "Asia"),
        Country(name: "Namibia", flag: "🇳🇦", isoCode: "NA", continent: "Africa"),
        Country(name: "Nauru", flag: "🇳🇷", isoCode: "NR", continent: "Oceania"),
        Country(name: "Nepal", flag: "🇳🇵", isoCode: "NP", continent: "Asia"),
        Country(name: "Netherlands", flag: "🇳🇱", isoCode: "NL", continent: "Europe"),
        Country(name: "New Zealand", flag: "🇳🇿", isoCode: "NZ", continent: "Oceania"),
        Country(name: "Nicaragua", flag: "🇳🇮", isoCode: "NI", continent: "North America"),
        Country(name: "Niger", flag: "🇳🇪", isoCode: "NE", continent: "Africa"),
        Country(name: "Nigeria", flag: "🇳🇬", isoCode: "NG", continent: "Africa"),
        Country(name: "North Korea", flag: "🇰🇵", isoCode: "KP", continent: "Asia"),
        Country(name: "North Macedonia", flag: "🇲🇰", isoCode: "MK", continent: "Europe"),
        Country(name: "Norway", flag: "🇳🇴", isoCode: "NO", continent: "Europe"),
        Country(name: "Oman", flag: "🇴🇲", isoCode: "OM", continent: "Asia"),
        Country(name: "Pakistan", flag: "🇵🇰", isoCode: "PK", continent: "Asia"),
        Country(name: "Palau", flag: "🇵🇼", isoCode: "PW", continent: "Oceania"),
        Country(name: "Palestine", flag: "🇵🇸", isoCode: "PS", continent: "Asia"),
        Country(name: "Panama", flag: "🇵🇦", isoCode: "PA", continent: "North America"),
        Country(name: "Papua New Guinea", flag: "🇵🇬", isoCode: "PG", continent: "Oceania"),
        Country(name: "Paraguay", flag: "🇵🇾", isoCode: "PY", continent: "South America"),
        Country(name: "Peru", flag: "🇵🇪", isoCode: "PE", continent: "South America"),
        Country(name: "Philippines", flag: "🇵🇭", isoCode: "PH", continent: "Asia"),
        Country(name: "Poland", flag: "🇵🇱", isoCode: "PL", continent: "Europe"),
        Country(name: "Portugal", flag: "🇵🇹", isoCode: "PT", continent: "Europe"),
        Country(name: "Qatar", flag: "🇶🇦", isoCode: "QA", continent: "Asia"),
        Country(name: "Romania", flag: "🇷🇴", isoCode: "RO", continent: "Europe"),
        Country(name: "Russia", flag: "🇷🇺", isoCode: "RU", continent: "Europe"),
        Country(name: "Rwanda", flag: "🇷🇼", isoCode: "RW", continent: "Africa"),
        Country(name: "Saint Kitts and Nevis", flag: "🇰🇳", isoCode: "KN", continent: "North America"),
        Country(name: "Saint Lucia", flag: "🇱🇨", isoCode: "LC", continent: "North America"),
        Country(name: "Saint Vincent and the Grenadines", flag: "🇻🇨", isoCode: "VC", continent: "North America"),
        Country(name: "Samoa", flag: "🇼🇸", isoCode: "WS", continent: "Oceania"),
        Country(name: "San Marino", flag: "🇸🇲", isoCode: "SM", continent: "Europe"),
        Country(name: "Sao Tome and Principe", flag: "🇸🇹", isoCode: "ST", continent: "Africa"),
        Country(name: "Saudi Arabia", flag: "🇸🇦", isoCode: "SA", continent: "Asia"),
        Country(name: "Senegal", flag: "🇸🇳", isoCode: "SN", continent: "Africa"),
        Country(name: "Serbia", flag: "🇷🇸", isoCode: "RS", continent: "Europe"),
        Country(name: "Seychelles", flag: "🇸🇨", isoCode: "SC", continent: "Africa"),
        Country(name: "Sierra Leone", flag: "🇸🇱", isoCode: "SL", continent: "Africa"),
        Country(name: "Singapore", flag: "🇸🇬", isoCode: "SG", continent: "Asia"),
        Country(name: "Slovakia", flag: "🇸🇰", isoCode: "SK", continent: "Europe"),
        Country(name: "Slovenia", flag: "🇸🇮", isoCode: "SI", continent: "Europe"),
        Country(name: "Solomon Islands", flag: "🇸🇧", isoCode: "SB", continent: "Oceania"),
        Country(name: "Somalia", flag: "🇸🇴", isoCode: "SO", continent: "Africa"),
        Country(name: "South Africa", flag: "🇿🇦", isoCode: "ZA", continent: "Africa"),
        Country(name: "South Korea", flag: "🇰🇷", isoCode: "KR", continent: "Asia"),
        Country(name: "South Sudan", flag: "🇸🇸", isoCode: "SS", continent: "Africa"),
        Country(name: "Spain", flag: "🇪🇸", isoCode: "ES", continent: "Europe"),
        Country(name: "Sri Lanka", flag: "🇱🇰", isoCode: "LK", continent: "Asia"),
        Country(name: "Sudan", flag: "🇸🇩", isoCode: "SD", continent: "Africa"),
        Country(name: "Suriname", flag: "🇸🇷", isoCode: "SR", continent: "South America"),
        Country(name: "Sweden", flag: "🇸🇪", isoCode: "SE", continent: "Europe"),
        Country(name: "Switzerland", flag: "🇨🇭", isoCode: "CH", continent: "Europe"),
        Country(name: "Syria", flag: "🇸🇾", isoCode: "SY", continent: "Asia"),
        Country(name: "Taiwan", flag: "🇹🇼", isoCode: "TW", continent: "Asia"),
        Country(name: "Tajikistan", flag: "🇹🇯", isoCode: "TJ", continent: "Asia"),
        Country(name: "Tanzania", flag: "🇹🇿", isoCode: "TZ", continent: "Africa"),
        Country(name: "Thailand", flag: "🇹🇭", isoCode: "TH", continent: "Asia"),
        Country(name: "Timor-Leste", flag: "🇹🇱", isoCode: "TL", continent: "Asia"),
        Country(name: "Togo", flag: "🇹🇬", isoCode: "TG", continent: "Africa"),
        Country(name: "Tonga", flag: "🇹🇴", isoCode: "TO", continent: "Oceania"),
        Country(name: "Trinidad and Tobago", flag: "🇹🇹", isoCode: "TT", continent: "North America"),
        Country(name: "Tunisia", flag: "🇹🇳", isoCode: "TN", continent: "Africa"),
        Country(name: "Turkey", flag: "🇹🇷", isoCode: "TR", continent: "Asia"),
        Country(name: "Turkmenistan", flag: "🇹🇲", isoCode: "TM", continent: "Asia"),
        Country(name: "Tuvalu", flag: "🇹🇻", isoCode: "TV", continent: "Oceania"),
        Country(name: "Uganda", flag: "🇺🇬", isoCode: "UG", continent: "Africa"),
        Country(name: "Ukraine", flag: "🇺🇦", isoCode: "UA", continent: "Europe"),
        Country(name: "United Arab Emirates", flag: "🇦🇪", isoCode: "AE", continent: "Asia"),
        Country(name: "United Kingdom", flag: "🇬🇧", isoCode: "GB", continent: "Europe"),
        Country(name: "United States", flag: "🇺🇸", isoCode: "US", continent: "North America"),
        Country(name: "Uruguay", flag: "🇺🇾", isoCode: "UY", continent: "South America"),
        Country(name: "Uzbekistan", flag: "🇺🇿", isoCode: "UZ", continent: "Asia"),
        Country(name: "Vanuatu", flag: "🇻🇺", isoCode: "VU", continent: "Oceania"),
        Country(name: "Venezuela", flag: "🇻🇪", isoCode: "VE", continent: "South America"),
        Country(name: "Vietnam", flag: "🇻🇳", isoCode: "VN", continent: "Asia"),
        Country(name: "Yemen", flag: "🇾🇪", isoCode: "YE", continent: "Asia"),
        Country(name: "Zambia", flag: "🇿🇲", isoCode: "ZM", continent: "Africa"),
        Country(name: "Zimbabwe", flag: "🇿🇼", isoCode: "ZW", continent: "Africa")
    ]
}
